//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales()
        {
            this.ProductSales = new HashSet<ProductSales>();
        }
    
        public int ID_Sale { get; set; }
        public int Product_ID { get; set; }
        public int Customer_ID { get; set; }
        public string PaymentMethod { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int TotalCost { get; set; }
        public Nullable<int> Store_ID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSales> ProductSales { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
